# Generated by Django 6.0.6 on 2026-07-28 19:00

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from ..models import AscentUnits2


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# bike.migrations.0049_auto_20250913_1451
##    in a new installation, there will be no pre-existing rides, so this is
##    probably not required, but included for consistency with Django migration
##    logic
def migrate_ride_ascent(apps, _schema_editor):
    """ manual data migration of bike.ride.ascent to .ascent_metres 
        copied from bike.migrations.0049_auto_20250913_1451 """
    # We can't import the Ride model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Ride = apps.get_model("bike", "Ride")
    for ride in Ride.objects.all():
        ride.ascent_metres = AscentUnits2.to_metres(ride.ascent_units, ride.ascent)
        ride.save()


class Migration(migrations.Migration):

    replaces = [
        ('bike', '0001_squashed_0047_auto_20250528_2007'),
        ('bike', '0048_prefs2_ride_ascent_metres_and_more'),
        ('bike', '0049_auto_20250913_1451'),
        ('bike', '0050_remove_ride_ascent_units'),
        ('bike', '0051_remove_componentchange_distance_units_and_more'),
        ('bike', '0052_delete_prefs2_remove_odometer_distance_units'),
        ('bike', '0053_preferences_place_nearby_search_distance_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to=settings.AUTH_USER_MODEL)),
                ('current_odo', models.FloatField(default=0, help_text='calculated current odometer, in distance units from preferences.')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('subtype_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subtypes', to='bike.componenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_types', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specification', models.CharField(blank=True, max_length=200, null=True)),
                ('date_acquired', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, max_length=400, null=True)),
                ('bike', models.ForeignKey(blank=True, help_text='Leave blank if this is a subcomponent of another part of a bike.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='bike.bike')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to=settings.AUTH_USER_MODEL)),
                ('subcomponent_of', models.ForeignKey(blank=True, help_text='Leave blank if this is a direct subcomponent of a bike', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='bike.component')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='bike.componenttype')),
                ('previous_distance', models.FloatField(default=0, help_text='odometer from previous bikes, in distance units from preferences.')),
                ('start_odo', models.FloatField(default=0, help_text='odometer when added to this bike, in distance units from preferences.')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(blank=True, null=True)),
                ('distance_units', models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Kilometres')], default=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ascent', models.FloatField(blank=True, null=True)),
                ('ascent_units', models.PositiveSmallIntegerField(choices=[(1, 'm'), (2, 'Ft')], default=1)),
                ('bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='bike.bike')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField(default='missing description', max_length=400)),
                ('is_adjustment', models.BooleanField(default=False, help_text='If true, signifies this is not a real ride but a ride distance adjustment between odometer readings.')),
                ('ascent_metres', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('rider', 'date', 'bike', 'description')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('reference_info', models.CharField(blank=True, max_length=300, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('maintenance_interval_distance', models.PositiveIntegerField(blank=True, null=True)),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_types', to='bike.componenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_types', to=settings.AUTH_USER_MODEL)),
                ('maint_interval_days', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('component_type', 'description')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(blank=True, help_text='you only need to specify one of bike or component.', null=True, on_delete=django.db.models.deletion.CASCADE, to='bike.component')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_actions', to=settings.AUTH_USER_MODEL)),
                ('maint_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bike.maintenancetype')),
                ('bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maint_actions', to='bike.bike')),
                ('completed', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('due_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('maintenance_interval_distance', models.PositiveIntegerField(blank=True, null=True)),
                ('maint_interval_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('due_distance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'bike', 'component', 'maint_type', 'description', 'due_date', 'due_distance')},
            },
        ),
        migrations.CreateModel(
            name='MaintActionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('maint_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='bike.maintenanceaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prefs2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_unit', models.SmallIntegerField(choices=[(10, 'Miles'), (20, 'Kilometres')], default=10)),
                ('distance_metres', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ComponentChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(blank=True, null=True)),
                ('distance_units', models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Kilometres')], default=10)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('description', models.CharField(max_length=200)),
                ('changed_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_history', to='bike.component')),
                ('parent_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomponent_history', to='bike.component')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceActionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_action', to='bike.maintenanceaction')),
                ('distance_units', models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Kilometres')], default=10)),
                ('component', models.ForeignKey(blank=True, help_text='you only need to specify one of bike or component.', null=True, on_delete=django.db.models.deletion.CASCADE, to='bike.component')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maint_history', to='bike.bike')),
            ],
            options={
                'verbose_name_plural': 'Maintenance action history',
            },
        ),
        migrations.CreateModel(
            name='Odometer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('distance_units', models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Kilometres')], default=10)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_readings', to='bike.bike')),
                ('initial_value', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('adjustment_ride', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bike.ride')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Odometer reading',
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('distance_units', models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Kilometres')], default=10)),
                ('ascent_units', models.PositiveSmallIntegerField(choices=[(1, 'Metres'), (2, 'Feet')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('maint_distance_limit', models.PositiveSmallIntegerField(blank=True, default=100, null=True, verbose_name='Upcoming maintenance distance limit')),
                ('maint_time_limit', models.DurationField(blank=True, default=datetime.timedelta(days=10), null=True, verbose_name='Upcoming maintenance time limit')),
            ],
            options={
                'verbose_name_plural': 'preferences',
            },
        ),
        ## probably not required as in an initial migration, there are no
        ## Ride instances to migrate
        migrations.RunPython(
            code=migrate_ride_ascent,
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ascent_units',
        ),
        migrations.RemoveField(
            model_name='componentchange',
            name='distance_units',
        ),
        migrations.RemoveField(
            model_name='maintenanceactionhistory',
            name='distance_units',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='distance_units',
        ),
        migrations.DeleteModel(
            name='Prefs2',
        ),
        migrations.RemoveField(
            model_name='odometer',
            name='distance_units',
        ),
        migrations.AddField(
            model_name='preferences',
            name='place_nearby_search_distance',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='place_search_result_limit',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='preferences',
            name='track_nearby_search_distance',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='preferences',
            name='track_search_result_limit',
            field=models.IntegerField(default=50),
        ),
    ]
