# Generated by Django 2.2.12 on 2020-05-11 22:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specification', models.CharField(max_length=200)),
                ('date_acquired', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('supplier', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=400)),
                ('bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='bike.Bike')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to=settings.AUTH_USER_MODEL)),
                ('subcomponent_of', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='bike.Component')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('maintenance_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('maint_interval_units', models.PositiveSmallIntegerField(choices=[(101, 'Miles'), (102, 'Kilometres'), (103, 'Days'), (104, 'Years')])),
                ('subtype_of', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtypes', to='bike.ComponentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_types', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('distance_units', models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Kilometres')])),
                ('date', models.DateField(default=datetime.date.today)),
                ('ascent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('ascent_units', models.PositiveSmallIntegerField(choices=[(1, 'Metres'), (2, 'Feet')])),
                ('bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='bike.Bike')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Odometer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('distance_units', models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Kilometres')])),
                ('date', models.DateField(default=datetime.date.today)),
                ('comment', models.CharField(max_length=100)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_readings', to='bike.Bike')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('reference_info', models.CharField(max_length=300)),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.ComponentType')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('distance_units', models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Kilometres')])),
                ('completed_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.Component')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('distance_units', models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Kilometres')])),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('description', models.CharField(max_length=200)),
                ('changed_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_history', to='bike.Component')),
                ('parent_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomponent_history', to='bike.Component')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike.ComponentType'),
        ),
    ]
