# Generated by Django 2.2.12 on 2020-05-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
