# Generated by Django 2.2.12 on 2020-05-12 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_ride_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='componentchange',
            name='distance_units',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Km')], default=10),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='subtype_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subtypes', to='bike.ComponentType'),
        ),
        migrations.AlterField(
            model_name='maintenanceaction',
            name='distance_units',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Km')], default=10),
        ),
        migrations.AlterField(
            model_name='odometer',
            name='distance_units',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Km')], default=10),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ascent_units',
            field=models.PositiveSmallIntegerField(choices=[(1, 'm'), (2, 'Ft')]),
        ),
        migrations.AlterField(
            model_name='ride',
            name='distance_units',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Km')], default=10),
        ),
    ]
