# Generated by Django 2.2.12 on 2020-05-12 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_auto_20200512_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='subcomponent_of',
            field=models.ForeignKey(blank=True, help_text='leave blank if this is a direct subcomponent of a bike', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='bike.Component'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
