# Generated by Django 2.2.12 on 2020-05-12 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0005_auto_20200512_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_units', models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Km')], default=10)),
                ('ascent_units', models.PositiveSmallIntegerField(choices=[(1, 'm'), (2, 'Ft')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
