# Generated by Django 2.2.12 on 2020-05-12 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0006_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='id',
        ),
        migrations.AlterField(
            model_name='preferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
