# Generated by Django 2.2.12 on 2020-05-16 11:39

import bike.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0007_auto_20200512_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferences',
            options={'verbose_name_plural': 'preferences'},
        ),
        migrations.AlterField(
            model_name='component',
            name='notes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='specification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='componentchange',
            name='distance_units',
            field=models.PositiveSmallIntegerField(choices=[(10, 'MILES'), (20, 'KILOMETRES')], default=bike.models.DistanceUnits(10)),
        ),
        migrations.AlterField(
            model_name='maintenanceaction',
            name='distance_units',
            field=models.PositiveSmallIntegerField(choices=[(10, 'MILES'), (20, 'KILOMETRES')], default=bike.models.DistanceUnits(10)),
        ),
        migrations.AlterField(
            model_name='odometer',
            name='distance_units',
            field=models.PositiveSmallIntegerField(choices=[(10, 'MILES'), (20, 'KILOMETRES')], default=bike.models.DistanceUnits(10)),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='distance_units',
            field=models.PositiveSmallIntegerField(choices=[(10, 'MILES'), (20, 'KILOMETRES')], default=bike.models.DistanceUnits(10)),
        ),
        migrations.AlterField(
            model_name='ride',
            name='distance_units',
            field=models.PositiveSmallIntegerField(choices=[(10, 'MILES'), (20, 'KILOMETRES')], default=bike.models.DistanceUnits(10)),
        ),
    ]
