# Generated by Django 2.2.12 on 2020-05-20 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0008_auto_20200516_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='bike',
            field=models.ForeignKey(blank=True, help_text='Leave blank if this is a subcomponent of another part of a bike.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='bike.Bike'),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='maint_interval_units',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(101, 'Miles'), (102, 'Kilometres'), (103, 'Days'), (104, 'Years')], null=True),
        ),
    ]
