# Generated by Django 2.2.12 on 2020-05-21 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0010_auto_20200521_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceaction',
            name='component',
            field=models.ForeignKey(blank=True, help_text='you only need to specify one of bike or component.', null=True, on_delete=django.db.models.deletion.CASCADE, to='bike.Component'),
        ),
        migrations.AlterUniqueTogether(
            name='maintenanceaction',
            unique_together={('user', 'bike', 'component', 'activity_type', 'description', 'due_date', 'distance')},
        ),
    ]
