# Generated by Django 2.2.12 on 2020-05-22 09:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0011_auto_20200521_2138'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ride',
            unique_together={('rider', 'date', 'bike', 'description')},
        ),
    ]
