# Generated by Django 2.2.12 on 2020-05-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0013_auto_20200527_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetype',
            name='reference_info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
