# Generated by Django 2.2.12 on 2020-05-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0014_auto_20200527_1051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maintenancetype',
            unique_together={('component_type', 'activity')},
        ),
    ]
