# Generated by Django 2.2.12 on 2020-05-27 09:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0015_auto_20200527_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenanceaction',
            old_name='activity_type',
            new_name='maint_type',
        ),
        migrations.AlterUniqueTogether(
            name='maintenanceaction',
            unique_together={('user', 'bike', 'component', 'maint_type', 'description', 'due_date', 'distance')},
        ),
    ]
