# Generated by Django 2.2.12 on 2020-05-27 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0016_auto_20200527_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odometer',
            name='date',
        ),
        migrations.AddField(
            model_name='odometer',
            name='initial',
            field=models.BooleanField(default=False, help_text='Only tick this for the initial value of new odometer or after resetting the odometer reading.'),
        ),
        migrations.AddField(
            model_name='odometer',
            name='reading_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='odometer',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
