# Generated by Django 2.2.12 on 2020-05-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0018_auto_20200527_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odometer',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
