# Generated by Django 2.2.12 on 2020-05-29 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0019_auto_20200528_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odometer',
            options={'verbose_name': 'Odometer reading'},
        ),
        migrations.AddField(
            model_name='odometer',
            name='adjustment_ride',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bike.Ride'),
        ),
        migrations.AddField(
            model_name='ride',
            name='is_adjustment',
            field=models.BooleanField(default=False, help_text='If true, signifies this is not a real ride but a ride distance adjustment between odometer readings.'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
