# Generated by Django 2.2.12 on 2020-05-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0022_auto_20200529_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentchange',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceaction',
            name='completed_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceaction',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odometer',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ascent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
