# Generated by Django 2.2.12 on 2020-05-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0023_auto_20200530_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odometer',
            name='adjustment_ride',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bike.Ride'),
        ),
    ]
