# Generated by Django 2.2.12 on 2020-07-27 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0026_bike_current_odo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceaction',
            name='maint_interval_units',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(101, 'Miles'), (102, 'Kilometres'), (103, 'Days'), (104, 'Years')], null=True),
        ),
        migrations.AddField(
            model_name='maintenanceaction',
            name='maintenance_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MaintenanceActionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('completed_distance', models.FloatField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_action', to='bike.MaintenanceAction')),
            ],
        ),
    ]
