# Generated by Django 2.2.12 on 2020-07-27 11:01
# Dummy Data migration:
# migrate completed maint actions to MaintenanceHistory model entries - moved
# to migration 0030

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0027_auto_20200727_1127'),
    ]

    operations = [
    ]
