# Generated by Django 2.2.12 on 2020-07-27 14:32

import bike.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0028_auto_20200727_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenanceactionhistory',
            old_name='completed_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='maintenanceactionhistory',
            old_name='completed_distance',
            new_name='distance',
        ),
        migrations.AddField(
            model_name='maintenanceactionhistory',
            name='distance_units',
            field=models.PositiveSmallIntegerField(choices=[(10, 'miles'), (20, 'kilometres')], default=bike.models.DistanceUnits(10)),
        ),
    ]
