# Generated by Django 2.2.12 on 2020-07-27 14:35
# Data migration:
# migrate completed maint actions to MaintenanceHistory model entries

from django.db import migrations


""" these two manual migration functions converted all old-style
completed MaintenanceActions to new MaintenanceActionHistory objects.
All the old-style actions have now been converted so these functions are
not required in using the squashed migration 0001-squashed-0047 """  

def migrate_completed_maint(apps, schema_editor):
    # can't just import them because they may change in the migration sequence
    MaintenanceAction = apps.get_model('bike', 'MaintenanceAction')
    MaintenanceActionHistory = apps.get_model(
        'bike', 'MaintenanceActionHistory')

    completed_maint = MaintenanceAction.objects.exclude(
        completed_date__isnull=True, completed_distance__isnull=True)

    for action in completed_maint.all():
        history = MaintenanceActionHistory(
            action=action, date=action.completed_date,
            distance=action.completed_distance,
            distance_units=action.distance_units)
        history.save()
        action.completed_distance = None
        action.completed_date = None
        action.save()


def revert_completed_maint(apps, schema_editor):
    # can't just import them because they may change in the migration sequence
    MaintenanceAction = apps.get_model('bike', 'MaintenanceAction')
    MaintenanceActionHistory = apps.get_model(
        'bike', 'MaintenanceActionHistory')

    maint_history = (MaintenanceActionHistory.objects
                     .order_by('-distance', '-date'))  # latest first
    for history in maint_history.all():
        action = history.action
        # check maintenance action doesn't already have completed-XXX
        # and history has distance, the units must match the maint action
        if (action.completed_distance is None and action.completed_date is None
            and (history.distance is None or
                 action.distance_units == history.distance_units)):
            # OK: copy maint history back into the maint action
            action.completed_distance = history.distance
            action.completed_date = history.date
            action.save()
        else:  # need to make a new one-off maint action to record the history
            new_action = MaintenanceAction(
                user=action.user, bike=action.bike,
                component=action.component, maint_type=action.maint_type,
                description=action.description, due_date=action.due_date,
                distance=action.distance,
                completed=True,
                completed_distance=history.distance,
                completed_date=history.date,
                distance_units=history.distance_units)
            new_action.save()
        history.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0029_auto_20200727_1532'),
    ]

    operations = [
        migrations.RunPython(migrate_completed_maint, revert_completed_maint),
    ]
