# Generated by Django 2.2.16 on 2021-05-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0030_auto_20200727_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceactionhistory',
            options={'verbose_name_plural': 'Maintenance action history'},
        ),
        migrations.RenameField(
            model_name='odometer',
            old_name='initial',
            new_name='initial_value',
        ),
    ]
