# Generated by Django 2.2.20 on 2021-05-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0031_auto_20210503_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componenttype',
            name='maintenance_type',
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_type', to='bike.ComponentType'),
        ),
        migrations.AlterField(
            model_name='odometer',
            name='initial_value',
            field=models.BooleanField(default=False),
        ),
    ]
