# Generated by Django 2.2.20 on 2021-05-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0032_auto_20210520_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenanceaction',
            old_name='maint_interval_units',
            new_name='maint_interval_distance_units',
        ),
        migrations.RenameField(
            model_name='maintenanceaction',
            old_name='maintenance_interval',
            new_name='maintenance_interval_distance',
        ),
        migrations.RenameField(
            model_name='maintenancetype',
            old_name='maint_interval_units',
            new_name='maint_interval_distance_units',
        ),
        migrations.RenameField(
            model_name='maintenancetype',
            old_name='maintenance_interval',
            new_name='maintenance_interval_distance',
        ),
        migrations.AddField(
            model_name='maintenanceaction',
            name='maint_interval_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='maint_interval_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
