# Generated by Django 2.2.20 on 2021-05-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0033_auto_20210522_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenanceactionhistory',
            old_name='date',
            new_name='completed_date',
        ),
        migrations.RenameField(
            model_name='maintenancetype',
            old_name='activity',
            new_name='description',
        ),
        migrations.AddField(
            model_name='maintenanceaction',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenanceactionhistory',
            name='completed_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceactionhistory',
            name='component',
            field=models.ForeignKey(blank=True, help_text='you only need to specify one of bike or component.', null=True, on_delete=django.db.models.deletion.CASCADE, to='bike.Component'),
        ),
        migrations.AddField(
            model_name='maintenanceactionhistory',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceaction',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceactionhistory',
            name='distance_units',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(101, 'Miles'), (102, 'Kilometres'), (103, 'Days'), (104, 'Years')], null=True),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_type', to='bike.ComponentType'),
        ),
        migrations.AlterUniqueTogether(
            name='maintenancetype',
            unique_together={('component_type', 'description')},
        ),
    ]
