# Generated by Django 2.2.20 on 2021-05-22 20:23

import bike.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0034_auto_20210522_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceactionhistory',
            name='completed_distance',
        ),
        migrations.AlterField(
            model_name='maintenanceactionhistory',
            name='distance_units',
            field=models.PositiveSmallIntegerField(choices=[(10, 'miles'), (20, 'kilometres')], default=bike.models.DistanceUnits(10)),
        ),
    ]
