# Generated by Django 2.2.20 on 2021-05-24 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0035_auto_20210522_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceactionhistory',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maint_history', to='bike.Bike'),
        ),
    ]
