# Generated by Django 2.2.20 on 2021-05-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0038_auto_20210525_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceaction',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='maintenanceaction',
            name='completed_distance',
        ),
        migrations.RemoveField(
            model_name='maintenanceaction',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='maintenanceaction',
            name='distance_units',
        ),
    ]
