# Generated by Django 2.2.20 on 2021-05-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0039_auto_20210525_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceaction',
            name='maint_interval_distance_units',
        ),
        migrations.RemoveField(
            model_name='maintenancetype',
            name='maint_interval_distance_units',
        ),
    ]
