# Generated by Django 2.2.20 on 2021-07-03 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0040_auto_20210531_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='maint_distance_limit',
            field=models.PositiveSmallIntegerField(blank=True, default=100, null=True, verbose_name='Upcoming maintenance distance limit'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='maint_time_limit',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=10), null=True, verbose_name='Upcoming maintenance time limit'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_types', to='bike.ComponentType'),
        ),
    ]
