# Generated by Django 2.2.20 on 2021-07-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0041_auto_20210703_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='bike.ComponentType'),
        ),
    ]
