# Generated by Django 2.2.20 on 2021-07-20 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0042_auto_20210706_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='notes',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.CreateModel(
            name='MaintActionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField()),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('maint_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='bike.MaintenanceAction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
