# Generated by Django 2.2.20 on 2021-07-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0043_auto_20210720_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintactionlink',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
