# Generated by Django 4.1 on 2022-08-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0044_auto_20210720_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='previous_distance',
            field=models.FloatField(default=0, help_text='odometer from previous bikes, in distance units from preferences.'),
        ),
        migrations.AddField(
            model_name='component',
            name='start_odo',
            field=models.FloatField(default=0, help_text='odometer when added to this bike, in distance units from preferences.'),
        ),
        migrations.CreateModel(
            name='ReplacementActionHistory',
            fields=[
                ('maintenanceactionhistory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bike.maintenanceactionhistory')),
                ('replaced_component', models.ForeignKey(blank=True, help_text='you only need to specify one of bike or component.', null=True, on_delete=django.db.models.deletion.CASCADE, to='bike.component')),
            ],
            options={
                'abstract': False,
            },
            bases=('bike.maintenanceactionhistory',),
        ),
    ]
