# Generated by Django 3.2.2 on 2023-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0045_component_previous_distance_component_start_odo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='description',
            field=models.TextField(default='missing description', max_length=400),
            preserve_default=False,
        ),
    ]
