# Generated by Django 3.2.2 on 2025-05-28 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0046_alter_ride_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='subcomponent_of',
            field=models.ForeignKey(blank=True, help_text='Leave blank if this is a direct subcomponent of a bike', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='bike.component'),
        ),
        migrations.AlterField(
            model_name='odometer',
            name='adjustment_ride',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bike.ride'),
        ),
        migrations.DeleteModel(
            name='ReplacementActionHistory',
        ),
    ]
