# Generated by Django 5.2.3 on 2025-09-13 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_squashed_0047_auto_20250528_2007'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefs2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_unit', models.SmallIntegerField(choices=[(10, 'Miles'), (20, 'Kilometres')], default=10)),
                ('distance_metres', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='ascent_metres',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='componentchange',
            name='distance_units',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Kilometres')], default=10),
        ),
        migrations.AlterField(
            model_name='maintenanceactionhistory',
            name='distance_units',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Kilometres')], default=10),
        ),
        migrations.AlterField(
            model_name='odometer',
            name='distance_units',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Kilometres')], default=10),
        ),
        migrations.AlterField(
            model_name='odometer',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='ascent_units',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Metres'), (2, 'Feet')], default=1),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='distance_units',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Kilometres')], default=10),
        ),
        migrations.AlterField(
            model_name='ride',
            name='distance_units',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Miles'), (20, 'Kilometres')], default=10),
        ),
    ]
