# Generated by Django 5.2.3 on 2025-09-13 13:51

from django.db import migrations
from ..models import AscentUnits0

""" manual data migration of bike.ride.ascent to .ascent_metres """
def migrate_ride_ascent(apps, schema_editor):
    # We can't import the Ride model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Ride = apps.get_model("bike", "Ride")
    for ride in Ride.objects.all():
        ride.ascent_metres = AscentUnits0.to_metres(ride.ascent_units, ride.ascent)
        ride.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0048_prefs2_ride_ascent_metres_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_ride_ascent),
    ]
