# Generated by Django 5.2.3 on 2025-09-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0049_auto_20250913_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='ascent_units',
        ),
    ]
