# Generated by Django 5.2.3 on 2025-09-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0050_remove_ride_ascent_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentchange',
            name='distance_units',
        ),
        migrations.RemoveField(
            model_name='maintenanceactionhistory',
            name='distance_units',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='distance_units',
        ),
    ]
