# Generated by Django 5.2.3 on 2025-09-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0051_remove_componentchange_distance_units_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prefs2',
        ),
        migrations.RemoveField(
            model_name='odometer',
            name='distance_units',
        ),
    ]
