# Generated by Django 5.2.3 on 2025-09-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0052_delete_prefs2_remove_odometer_distance_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='place_nearby_search_distance',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='preferences',
            name='place_search_result_limit',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='preferences',
            name='track_nearby_search_distance',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='preferences',
            name='track_search_result_limit',
            field=models.IntegerField(default=50),
        ),
    ]
