# Generated by Django 3.2.2 on 2025-05-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track',
        ),
    ]
