# Generated by Django 3.2.2 on 2025-05-28 19:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_delete_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('track', django.contrib.gis.db.models.fields.MultiLineStringField(dim=3, srid=4326)),
                ('raw_gpx_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.rawgpx')),
            ],
        ),
    ]
