# Generated by Django 3.2.2 on 2025-05-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='raw_gpx_id',
        ),
        migrations.DeleteModel(
            name='RawGpx',
        ),
    ]
