# Generated by Django 3.2.2 on 2025-05-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20250528_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawGpx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='')),
            ],
        ),
    ]
