# Generated by Django 3.2.2 on 2025-05-28 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_rawgpx'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='raw_gpx_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.rawgpx'),
        ),
    ]
