# Generated by Django 5.2.3 on 2025-06-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_placetype_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetype',
            name='icon',
            field=models.CharField(choices=[('Beer', 'cup-straw-pink.svg'), ('Coffee', 'cup-orange.svg'), ('Tea', 'teapot.svg'), ('Place', 'geo-green.svg'), ('Camera', 'camera-yellow.svg'), ('Bullseye', 'bullseye-blue.svg')], default='geo-green.svg', max_length=30),
        ),
    ]
