# Generated by Django 5.2.3 on 2025-06-21 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_placetype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='routes.placetype'),
        ),
    ]
