# Generated by Django 5.2.3 on 2025-06-23 09:47

import django.db.models.deletion
import routes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_placetype_user_alter_place_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.ForeignKey(default=routes.models.get_default_place_type, on_delete=django.db.models.deletion.PROTECT, to='routes.placetype'),
        ),
    ]
