# Generated by Django 5.2.3 on 2025-06-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0016_track_ascent_track_end_time_track_moving_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='ascent',
            field=models.FloatField(blank=True, help_text='Ascent in metres', null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='moving_distance',
            field=models.FloatField(blank=True, help_text='Moving distance in metres', null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='moving_time',
            field=models.FloatField(blank=True, help_text='Moving time in seconds', null=True),
        ),
    ]
