# Generated by Django 5.2.3 on 2025-07-03 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0017_alter_track_ascent_alter_track_moving_distance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_name'),
        ),
    ]
