# Generated by Django 5.2.3 on 2025-07-07 22:07

import django.db.models.deletion
import routes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0018_track_unique_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.ForeignKey(default=routes.models.get_default_place_type_pk, on_delete=django.db.models.deletion.PROTECT, to='routes.placetype'),
        ),
        migrations.AddField(
            model_name='place',
            name='tag',
            field=models.ManyToManyField(related_name='place', to='routes.tag'),
        ),
        migrations.AddField(
            model_name='track',
            name='tag',
            field=models.ManyToManyField(related_name='track', to='routes.tag'),
        ),
    ]
