# Generated by Django 5.2.3 on 2025-07-22 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0020_tag_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='creator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placetype',
            name='icon',
            field=models.CharField(choices=[('Beer', 'cup-straw-pink.svg'), ('Coffee', 'cup-orange.svg'), ('Tea', 'teapot-brown-web.svg'), ('Place', 'geo-green.svg'), ('Camera', 'camera-yellow.svg'), ('Bullseye', 'bullseye-blue.svg')], default='geo-green.svg', max_length=30),
        ),
        migrations.AlterField(
            model_name='placetype',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
