# Generated by Django 5.2.3 on 2025-08-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0021_track_creator_track_description_alter_placetype_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_collation='NOCASE', max_length=20, unique=True),
        ),
    ]
