# Generated by Django 5.2.3 on 2025-09-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0022_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='raw_gpx_id',
        ),
        migrations.DeleteModel(
            name='RawGpx',
        ),
    ]
