# Generated by Django 5.2.3 on 2025-09-02 20:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0023_remove_track_raw_gpx_id_delete_rawgpx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_collation='NOCASE', max_length=40)),
                ('name', models.CharField(db_collation='NOCASE', max_length=40)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Boundaries',
                'constraints': [models.UniqueConstraint(fields=('user', 'category', 'name'), name='unique_boundary')],
            },
        ),
    ]
