# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-27 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kitten.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('started', models.DateField(auto_now_add=True)),
                ('last_played', models.DateField(auto_now=True)),
                ('network_name', models.CharField(max_length=40)),
                ('level', models.IntegerField(choices=[(10, 'Basic'), (20, 'Intermediate'), (30, 'Advanced'), (40, 'Expert')])),
            ],
            bases=(models.Model, kitten.models.GameLevel),
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_reputation', models.IntegerField(default=100)),
                ('name', models.CharField(default='', max_length=40)),
                ('direction1', models.CharField(default='Up', max_length=20)),
                ('direction2', models.CharField(default='Down', max_length=20)),
                ('trains_dir1', models.IntegerField(default=3)),
                ('trains_dir2', models.IntegerField(default=3)),
                ('train_interval', models.IntegerField(default=10)),
                ('train_type', models.CharField(default='Train', max_length=20)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitten.Game')),
            ],
        ),
        migrations.CreateModel(
            name='LineLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=40)),
                ('type', models.IntegerField(choices=[(0, 'Depot'), (1, 'Track'), (2, 'Station')], default=0)),
                ('sequence', models.IntegerField()),
                ('transit_delay', models.IntegerField(default=1)),
                ('direction', models.CharField(default='direction?', max_length=20)),
                ('direction_is_forward', models.BooleanField(default=True)),
                ('is_start_of_line', models.BooleanField(default=False)),
                ('is_end_of_line', models.BooleanField(default=False)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='kitten.Line')),
            ],
            bases=(models.Model, kitten.models.LocationType),
        ),
        migrations.CreateModel(
            name='LineTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('direction1', models.CharField(default='Up', max_length=20)),
                ('direction2', models.CharField(default='Down', max_length=20)),
                ('trains_dir1', models.IntegerField(default=3)),
                ('trains_dir2', models.IntegerField(default=3)),
                ('train_interval', models.IntegerField(default=10)),
                ('train_type', models.CharField(default='Train', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('created', models.DateField(auto_now_add=True)),
                ('last_saved', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='A name is only required for stations', max_length=40, verbose_name='Name (if station)')),
                ('type', models.IntegerField(choices=[(0, 'Depot'), (1, 'Track'), (2, 'Station')], default=0)),
                ('position', models.IntegerField()),
                ('transit_delay', models.IntegerField(default=1, help_text='Wait time at stations or depots')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='kitten.LineTemplate')),
            ],
            bases=(models.Model, kitten.models.LocationType),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='kitten.Line')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('level', models.IntegerField(choices=[(10, 'Basic'), (20, 'Intermediate'), (30, 'Advanced'), (40, 'Expert')])),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams_owned', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, kitten.models.GameLevel),
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Train', max_length=20)),
                ('serial', models.PositiveIntegerField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitten.LineLocation')),
            ],
        ),
        migrations.AddField(
            model_name='linetemplate',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kitten.Network'),
        ),
        migrations.AddField(
            model_name='line',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kitten.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(related_name='games', to='kitten.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='placetemplate',
            unique_together=set([('line', 'position')]),
        ),
    ]
