# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-27 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import kitten.models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(10, 'Basic'), (20, 'Intermediate'), (30, 'Advanced'), (40, 'Expert')])),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='kitten.Network')),
            ],
            bases=(models.Model, kitten.models.GameLevel),
        ),
        migrations.AlterUniqueTogether(
            name='gametemplate',
            unique_together=set([('network', 'level')]),
        ),
    ]
