# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-25 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_played',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='last_saved',
            field=models.DateField(auto_now=True),
        ),
    ]
