# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-25 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0002_auto_20200425_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLineParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('trains_dir1', models.IntegerField(default=3)),
                ('trains_dir2', models.IntegerField(default=3)),
                ('train_frequency', models.IntegerField(default=10)),
                ('reputation', models.IntegerField(default=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitten.Game')),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitten.Network')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitten.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('direction1', models.CharField(max_length=20)),
                ('direction2', models.CharField(max_length=20)),
                ('trains_dir1', models.IntegerField(default=3)),
                ('trains_dir2', models.IntegerField(default=3)),
                ('train_frequency', models.IntegerField(default=10)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitten.Network')),
            ],
        ),
    ]
