# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-27 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0002_auto_20200427_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kitten.Game'),
        ),
    ]
