# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-25 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0003_gamelineparameters_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='train_frequency',
            new_name='train_interval',
        ),
    ]
