# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-25 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0004_auto_20200425_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sequence', models.IntegerField()),
                ('transit_time', models.IntegerField(default=1)),
                ('location_type', models.IntegerField(choices=[(0, 'Depot'), (1, 'Track'), (2, 'Station')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitten.LineLocation')),
            ],
        ),
        migrations.AlterModelOptions(
            name='gamelineparameters',
            options={'verbose_name_plural': 'Game Line Parameters'},
        ),
        migrations.AddField(
            model_name='linelocation',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitten.GameLineParameters'),
        ),
    ]
