# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-27 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0004_auto_20200427_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetemplate',
            name='type',
            field=models.IntegerField(choices=[(0, 'Depot'), (1, 'Track'), (2, 'Station')], default=1),
        ),
    ]
