# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-25 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0005_auto_20200425_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team',
            field=models.ManyToManyField(related_name='games', to='kitten.Team'),
        ),
    ]
