# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-28 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0006_auto_20200428_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linelocation',
            old_name='sequence',
            new_name='position',
        ),
    ]
