# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-28 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0007_auto_20200428_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='delay',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='line',
            name='delay',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linelocation',
            name='last_train_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='linelocation',
            name='turnaround_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='placetemplate',
            name='turnaround_percent_direction1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='placetemplate',
            name='turnaround_percent_direction2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='line',
            name='direction1',
            field=models.CharField(default='Up', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='line',
            name='direction2',
            field=models.CharField(default='Down', editable=False, max_length=20),
        ),
    ]
