# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-28 08:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0009_auto_20200428_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='day_end_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='game',
            name='day_start_time',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
    ]
