# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-25 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0010_auto_20200425_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='linelocation',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitten.Line'),
        ),
        migrations.AlterField(
            model_name='line',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kitten.Network'),
        ),
    ]
