# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-25 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0011_auto_20200425_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linelocation',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitten.GameLineParameters'),
        ),
        migrations.AlterField(
            model_name='linelocation',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='kitten.Line'),
        ),
    ]
