# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-28 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0011_auto_20200428_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='awaiting_turnaround',
            field=models.BooleanField(default=False),
        ),
    ]
