# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-29 08:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0012_train_awaiting_turnaround'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='train',
            name='delay',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
