# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-29 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0013_auto_20200429_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='delay',
        ),
        migrations.AddField(
            model_name='line',
            name='on_time_arrivals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='line',
            name='total_arrivals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='line',
            name='total_delay',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
