# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-29 13:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0014_auto_20200429_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='?', max_length=40)),
                ('blocking', models.BooleanField(default=False)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='kitten.Network')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_start_time', models.DateTimeField(null=True)),
                ('response_start_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='?', max_length=40)),
                ('type', models.IntegerField(choices=[(1, 'Line'), (2, 'Train'), (3, 'Station')])),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('impacts', models.ManyToManyField(to='kitten.Impact')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_types', to='kitten.Network')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='?', max_length=40)),
                ('developer_description', models.CharField(blank=True, max_length=100, null=True)),
                ('effectiveness_percent', models.PositiveSmallIntegerField(default=100)),
                ('time_to_fix', models.DurationField(default=datetime.timedelta(0))),
                ('impacts', models.ManyToManyField(to='kitten.Impact')),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitten.Network')),
            ],
        ),
        migrations.AddField(
            model_name='incidenttype',
            name='responses',
            field=models.ManyToManyField(to='kitten.Response'),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitten.IncidentType'),
        ),
        migrations.AddField(
            model_name='incident',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitten.Line'),
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitten.LineLocation'),
        ),
        migrations.AddField(
            model_name='incident',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kitten.Response'),
        ),
    ]
