# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-26 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0014_auto_20200425_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'Basic'), (1, 'Intermediate'), (2, 'Advanced'), (4, 'Expert')])),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='kitten.Network')),
            ],
        ),
        migrations.CreateModel(
            name='LineTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kitten.Network')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='kitten.LineTemplate')),
            ],
        ),
        migrations.RemoveField(
            model_name='line',
            name='network',
        ),
        migrations.AlterUniqueTogether(
            name='gametemplate',
            unique_together=set([('network', 'level')]),
        ),
    ]
