# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-30 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0015_auto_20200429_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttype',
            name='chance_percent',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
