# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-26 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0015_auto_20200426_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetemplate',
            name='location_type',
            field=models.IntegerField(choices=[(0, 'Depot'), (1, 'Track'), (2, 'Station')], default=1),
        ),
        migrations.AddField(
            model_name='placetemplate',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gametemplate',
            name='level',
            field=models.IntegerField(choices=[(10, 'Basic'), (20, 'Intermediate'), (30, 'Advanced'), (40, 'Expert')]),
        ),
        migrations.AlterUniqueTogether(
            name='placetemplate',
            unique_together=set([('line', 'position')]),
        ),
    ]
