# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-30 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0016_incidenttype_chance_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='incident_types',
            field=models.ManyToManyField(null=True, to='kitten.IncidentType'),
        ),
    ]
