# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-26 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0017_auto_20200426_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placetemplate',
            name='name_if_station',
        ),
        migrations.AddField(
            model_name='placetemplate',
            name='name',
            field=models.CharField(help_text='A name is only required for stations', max_length=40, null=True, verbose_name='name if station'),
        ),
    ]
