# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-30 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0017_game_incident_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenttype',
            name='chance_percent',
        ),
        migrations.AddField(
            model_name='incidenttype',
            name='likelihood',
            field=models.PositiveSmallIntegerField(default=10, help_text='0-100: likelihood of this incident type occuring compared to other incident types'),
        ),
        migrations.AlterField(
            model_name='game',
            name='incident_types',
            field=models.ManyToManyField(to='kitten.IncidentType'),
        ),
    ]
