# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-26 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0018_auto_20200426_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetemplate',
            name='name',
            field=models.CharField(blank=True, help_text='A name is only required for stations', max_length=40, null=True, verbose_name='Name (if station)'),
        ),
    ]
