# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0018_auto_20200430_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='Untitled', max_length=40),
            preserve_default=False,
        ),
    ]
