# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-26 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0019_auto_20200426_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placetemplate',
            name='transit_time',
        ),
        migrations.AddField(
            model_name='placetemplate',
            name='transit_delay',
            field=models.IntegerField(default=1, help_text='Wait time at stations or depots'),
        ),
    ]
