# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-30 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0019_auto_20200430_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='incident_type',
            new_name='type',
        ),
    ]
