# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-30 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0020_auto_20200430_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='location',
        ),
        migrations.AddField(
            model_name='game',
            name='incident_rate',
            field=models.PositiveSmallIntegerField(default=100, help_text='average rate of incidents, with 100 generating1 incident per tick of the clock'),
        ),
        migrations.AddField(
            model_name='gametemplate',
            name='incident_rate',
            field=models.PositiveSmallIntegerField(default=100, help_text='average rate of incidents, with 100 generating1 incident per tick of the clock'),
        ),
        migrations.AddField(
            model_name='incident',
            name='location_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='kitten.LineLocation'),
        ),
        migrations.AddField(
            model_name='incident',
            name='location_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='kitten.Station'),
        ),
        migrations.AddField(
            model_name='incident',
            name='location_train',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='kitten.Train'),
        ),
    ]
