# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-30 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0021_auto_20200430_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='kitten.Line'),
        ),
    ]
