# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-30 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0022_auto_20200430_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='incident_start_time',
            new_name='start_time',
        ),
    ]
