# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-30 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0023_auto_20200430_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='impacts',
            field=models.ManyToManyField(to='kitten.Impact'),
        ),
    ]
