# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-05-01 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0024_incident_impacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='previous_response_status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='kitten.LineLocation'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='kitten.Station'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location_train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='kitten.Train'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='response_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
