# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-05-02 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0026_auto_20200502_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='level',
            field=models.IntegerField(choices=[(10, 'Basic'), (20, 'Intermediate'), (30, 'Advanced'), (40, 'Expert')], default=10),
        ),
    ]
