# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-05-03 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitten', '0028_auto_20200503_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='invitations',
        ),
        migrations.AddField(
            model_name='team',
            name='invitees',
            field=models.ManyToManyField(through='kitten.TeamInvitation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='invitee_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
