# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-05-03 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0030_auto_20200503_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaminvitation',
            old_name='invitation_date',
            new_name='date',
        ),
    ]
