# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-05-03 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0031_auto_20200503_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
