# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-05-04 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0032_teaminvitation_failed_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitten.Game')),
                ('invited_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to='kitten.Team')),
                ('inviting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to='kitten.Team')),
            ],
        ),
    ]
