# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-05-04 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0034_auto_20200504_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinvitation',
            name='invited_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_invitations', to='kitten.Team'),
        ),
    ]
