# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-05-04 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0035_auto_20200504_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='direction_is_forward',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='incident_rate',
            field=models.PositiveSmallIntegerField(default=50, help_text='average rate of incidents, with 100 generating1 incident per tick of the clock'),
        ),
    ]
