# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-05-05 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0036_auto_20200504_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linelocation',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitten.Line'),
        ),
        migrations.AlterField(
            model_name='station',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitten.Line'),
        ),
    ]
