# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-05-07 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0038_auto_20200505_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='one_time_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impact',
            name='recurring_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impact',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Line'), (20, 'Passenger'), (30, 'Staff'), (40, 'Cost')], default=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='incident_rate',
            field=models.PositiveSmallIntegerField(default=50, help_text='average rate of incidents, with 100 generating 1 incident per tick of the clock'),
        ),
        migrations.AlterField(
            model_name='game',
            name='network_name',
            field=models.CharField(help_text='A network is a\n     predefined collection of lines, trains and incident types to base your\n     game upon', max_length=40),
        ),
    ]
