# Generated by Django 2.2.12 on 2020-05-10 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0040_auto_20200508_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placetemplate',
            options={'ordering': ('position',)},
        ),
        migrations.AlterField(
            model_name='placetemplate',
            name='transit_delay',
            field=models.IntegerField(default=1, help_text='time to travel along lines; wait time at stations or depots'),
        ),
        migrations.AlterField(
            model_name='placetemplate',
            name='turnaround_percent_direction1',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='placetemplate',
            name='turnaround_percent_direction2',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='placetemplate',
            unique_together=set(),
        ),
    ]
