# Generated by Django 2.2.12 on 2020-05-12 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0041_auto_20200510_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='play_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Between days'), (1, 'Between stages'), (2, 'Paused'), (3, 'Running')], default=0),
        ),
        migrations.AddField(
            model_name='network',
            name='game_tick_interval',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
        migrations.AlterField(
            model_name='game',
            name='tick_interval',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
        migrations.AlterField(
            model_name='gametemplate',
            name='incident_rate',
            field=models.PositiveSmallIntegerField(default=50, help_text='average rate of incidents, with 100 generating 1 incident per tick of the clock, across the network'),
        ),
        migrations.AlterField(
            model_name='linetemplate',
            name='direction1',
            field=models.CharField(default='Up', help_text='for example, Westbound, Northbound, Clockwise', max_length=20),
        ),
        migrations.AlterField(
            model_name='linetemplate',
            name='direction2',
            field=models.CharField(default='Down', help_text='for the opposite direction', max_length=20),
        ),
        migrations.AlterField(
            model_name='linetemplate',
            name='train_interval',
            field=models.IntegerField(default=10, verbose_name='Interval between trains starting'),
        ),
        migrations.AlterField(
            model_name='linetemplate',
            name='trains_dir1',
            field=models.IntegerField(default=3, verbose_name='Number of trains starting in direction1'),
        ),
        migrations.AlterField(
            model_name='linetemplate',
            name='trains_dir2',
            field=models.IntegerField(default=3, verbose_name='Number of trains starting in direction2'),
        ),
    ]
