# Generated by Django 2.2.12 on 2020-05-15 11:51

from django.db import migrations, models
import django.db.models.deletion
import kitten.models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0042_auto_20200512_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='teams',
        ),
        migrations.AlterField(
            model_name='game',
            name='play_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'BETWEEN_DAYS'), (1, 'BETWEEN_STAGES'), (2, 'PAUSED'), (3, 'RUNNING'), (4, 'PLAY_REQUESTED'), (5, 'PAUSE_REQUESTED')], default=kitten.models.GamePlayStatus(0)),
        ),
        migrations.CreateModel(
            name='TeamGameStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_status', models.PositiveSmallIntegerField(choices=[(0, 'BETWEEN_DAYS'), (1, 'BETWEEN_STAGES'), (2, 'PAUSED'), (3, 'RUNNING'), (4, 'PLAY_REQUESTED'), (5, 'PAUSE_REQUESTED')], null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitten.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitten.Team')),
            ],
            options={
                'unique_together': {('team', 'game')},
            },
        ),
    ]
