# Generated by Django 2.2.12 on 2020-05-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0043_auto_20200515_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(related_name='games', through='kitten.TeamGameStatus', to='kitten.Team'),
        ),
    ]
