# Generated by Django 2.2.12 on 2020-05-16 09:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import kitten.models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0044_game_teams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamgamestatus',
            options={'verbose_name_plural': 'Team game status'},
        ),
        migrations.AlterField(
            model_name='game',
            name='day_end_time',
            field=models.TimeField(default=datetime.time(22, 0), help_text='time when daily train operations end, in UTC/GMT time'),
        ),
        migrations.AlterField(
            model_name='game',
            name='day_start_time',
            field=models.TimeField(default=datetime.time(6, 0), help_text='time when daily train operations start, in UTC/GMT time'),
        ),
        migrations.AlterField(
            model_name='game',
            name='play_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'BETWEEN_DAYS'), (1, 'BETWEEN_ROUNDS'), (2, 'PAUSED'), (3, 'RUNNING'), (4, 'PLAY_REQUESTED'), (5, 'PAUSE_REQUESTED')], default=kitten.models.GamePlayStatus(0)),
        ),
        migrations.AlterField(
            model_name='network',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='networks', to='kitten.Team'),
        ),
        migrations.AlterField(
            model_name='teamgamestatus',
            name='play_status',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Pause Requested'), (4, 'Play Requested')], null=True),
        ),
    ]
