# Generated by Django 2.2.12 on 2020-05-18 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0045_auto_20200516_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='night_traffic',
            field=models.PositiveIntegerField(default=50, help_text='passenger traffic at start/end of the day'),
        ),
        migrations.AddField(
            model_name='network',
            name='peak_evening_start',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='network',
            name='peak_evening_traffic',
            field=models.PositiveIntegerField(default=150, help_text='passenger traffic compared to daytime normal=100'),
        ),
        migrations.AddField(
            model_name='network',
            name='peak_morning_end',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='network',
            name='peak_morning_traffic',
            field=models.PositiveIntegerField(default=200, help_text='passenger traffic compared to daytime normal=100'),
        ),
        migrations.AddField(
            model_name='placetemplate',
            name='passenger_traffic_percent',
            field=models.PositiveSmallIntegerField(default=100, help_text='Relative passenger traffic at this station.'),
        ),
        migrations.AlterField(
            model_name='network',
            name='game_round_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), help_text='the amount of game time in a round of the game.  Should be a multiple of the game tick interval'),
        ),
        migrations.AlterField(
            model_name='network',
            name='game_tick_interval',
            field=models.DurationField(default=datetime.timedelta(seconds=300), help_text='The amount of game time that passes in a single iteration of simulation (where trains are moved, incidents happen etc.'),
        ),
    ]
