# Generated by Django 2.2.12 on 2020-05-18 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitten', '0046_auto_20200518_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='game_round_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), help_text='The amount of game time in a round of the game.  Should be a multiple of the game tick interval'),
        ),
        migrations.AlterField(
            model_name='network',
            name='game_tick_interval',
            field=models.DurationField(default=datetime.timedelta(seconds=300), help_text='The amount of game time that passes in a single iteration of simulation (where trains are moved, incidents happen etc.)'),
        ),
    ]
